name: act10ns-slack

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  act10ns-slack:
    name: act10ns-slack
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run act10ns-slack
        uses: step-security/act10ns-slack@main
        with:
          status: 'success'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
