name: action-surefire-report
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.21.x
      - run: |
          cd integration-tests/go && 
            go install github.com/jstemmer/go-junit-report/v2@latest &&
            go test -v 2>&1 ./... |
            go-junit-report -out report.xml
      - uses: step-security/action-surefire-report@release
        with:
          check_name: Example Go Report
          report_paths: integration-tests/go/report.xml
          file_name_in_stack_trace: true
