name: action-tflint
on: 
  workflow_dispatch:

jobs:
    lint-terraform:
        runs-on: ubuntu-latest
        steps:
            - name: linting
              uses: step-security/action-tflint@main
              with: 
                  github_token: ${{secrets.GITHUB_TOKEN}}
