name: action-get-latest-tag
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  action-get-latest-tag-main:
    name: Get Latest Tag (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get Latest Tag
        id: get-latest-tag
        uses: step-security/action-get-latest-tag@main
        with:
          semver_only: "true"
          with_initial_version: "true"
          initial_version: "v0.0.0"
      - name: Print tag
        run: echo "${{ steps.get-latest-tag.outputs.tag }}"
