name: action-slack-incoming-webhook
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  slack-incoming-webhook-main:
    name: Slack Incoming Webhook (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Slack Notification
        uses: step-security/action-slack-incoming-webhook@main
        with:
          text: "Hello from StepSecurity! \U0001F680"
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
