name: action-add-labels
on: 
  workflow_dispatch:

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:  
            - name: add-label
              uses: step-security/action-add-labels@main
              with:
                labels: chore
