name: action-markdown-lint
on: 
  workflow_dispatch:


jobs:
    lint-markdown:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: markdown-linting
              uses: step-security/action-markdownlint@main
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                reporter: "github-check"
                level: "warning"
                filter_mode: "nofilter"
                markdownlint_flags: ". -i README.md"
