
name: action-slack-notify

on:
  workflow_dispatch:

jobs:
  slackNotification-main:
    name: Slack Notification-main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Send Slack Notification
        uses: step-security/action-slack-notify@main
        env:
          SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
          SLACK_CHANNEL: general
          SLACK_USERNAME: step-security
          SLACK_ICON: https://github.com/step-security.png?size=48
          SLACK_TITLE: Test Notification
          SLACK_MESSAGE: 'Hello from StepSecurity! 🚀'
          SLACK_COLOR: ${{ job.status }}
