name: actions-aws-ssm-params-to-env

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  subscription-check:
    name: Subscription Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: step-security/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::478061329833:role/test-action
          aws-region: ap-south-1

      - name: Run actions-aws-ssm-params-to-env
        uses: step-security/actions-aws-ssm-params-to-env@main
        with:
          ssm-path: /test/param
