name: actions-aws-ssm-params-to-env

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  subscription-check:
    name: Subscription Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: step-security/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run actions-aws-ssm-params-to-env
        uses: step-security/actions-aws-ssm-params-to-env@release
        with:
          ssm-path: /test/param
