name: action-github-changelog-generator

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Generate changelog
        uses: step-security/action-github-changelog-generator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unreleasedOnly: true
