name: action-junit-report

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  junit-report-main:
    name: JUnit Report (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Publish JUnit Report
        uses: step-security/action-junit-report@main

