name: action-size

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  subscription-check:
    name: Subscription Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run action-size
        uses: step-security/action-size@release
