name: actions-oidc-debugger
on: 
  workflow_dispatch:

jobs:
    oidc-main:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:

            - name: oidc-print
              uses: step-security/actions-oidc-debugger@main
              with: 
                audience: "https://github.com/step-security"
