name: actions-setup-docker-compose

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Setup docker-compose
        uses: step-security/actions-setup-docker-compose@release
        with:
          version: '2.14.2'

      - name: Verify docker-compose installation
        run: docker-compose --version
