name: add-and-commit
on: 
  workflow_dispatch:
permissions:
  contents: write
jobs:
    commit:
        runs-on: ubuntu-latest
        steps:  
            - name: commit
              uses: step-security/add-and-commit@main
                
