
name: alls-green

on:
    workflow_dispatch:

jobs:
    succeeding:
        runs-on: ubuntu-latest
        timeout-minutes: 2
        steps:
          - run: exit 0
          
    all-green-main:
      needs:
      - succeeding
      if: always()
      runs-on: ubuntu-latest
      timeout-minutes: 2

      steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit  

      - name: all-green
        uses: step-security/alls-green@main
        with: 
            jobs: ${{ toJson(needs) }}
