name: auto-assign
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  auto-assign-with-pr:
    name: Auto Assign (release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Auto Assign Issues/PRs
        uses: step-security/wow-actions-auto-assign@fix/audit-packages
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          addReviewers: "true"
          addAssignees: "true"
          reviewers: "amanstep"
          assignees: "amanstep"
          numberOfReviewers: 1
          skipDraft: "true"
