name: aws-cloudformation-github-deploy
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  aws-cloudformation-github-deploy-main:
    name: AWS CloudFormation Deploy (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy CloudFormation Stack
        uses: step-security/aws-cloudformation-github-deploy@main
        with:
          name: test-stack
          template: testdata/aws-cloudformation-github-deploy/template.yml
          capabilities: CAPABILITY_IAM
          fail-on-empty-changeset: "0"
