name: azure-docker-login

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  azure-docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Login to container registry
        uses: step-security/azure-docker-login@main
        with:
          login-server: https://index.docker.io/v1/
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
