name: backport-github-action

on:
  pull_request_target:
    types: ["closed"]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport PR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Add backport label
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "backport-to-playground-v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Backport Action
        uses: step-security/backport-github-action@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-to-
