name: buf-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Buf Action
        uses: step-security/buf-action@release
        with:
          setup_only: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
