name: buf-setup-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buf-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup buf
        uses: step-security/buf-setup-action@release
        with:
          version: '1.50.0'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify buf installation
        run: buf --version
