name: cargo-semver-checks-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  cargo-semver-checks-main:
    name: Cargo Semver Checks (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test crate (ref_slice patch_change)
        uses: actions/checkout@v6
        with:
          repository: mgr0dzicki/cargo-semver-action-ref-slice
          ref: patch_change
      - name: Cargo Semver Checks
        uses: step-security/cargo-semver-checks-action@main
