name: chart-releaser-action

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  chart-releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: step-security/chart-releaser-action@main
        with:
          charts_dir: charts
          install_only: 'true'
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
