name: chrome-extension-upload

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  chrome-extension-upload:
    name: chrome-extension-upload
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run chrome-extension-upload
        uses: step-security/chrome-extension-upload@release
        with:
          file-path: testdata/chrome-extension-upload/extension.zip
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: 'false'
