name: contributor-assistant

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'testdata/contributor-assistant/**'
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  contributor-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: CLA Assistant
        uses: step-security/contributor-assistant-github-action@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/cla.json'
          branch: 'main'
          allowlist: dependabot[bot]
