name: cypress-io-github-action

on:
  workflow_dispatch:

jobs:
  subscription-check:
    name: Subscription Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Run Cypress Github Action
        uses: step-security/cypress-io-github-action@main
        with:
          working-directory: ./testdata/cypress-io-github-action
