name: dprint-check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dprint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: dprint-check
        uses: step-security/dprint-check@release
