name: eval-action

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  eval-action:
    name: eval-action
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install eval dependencies
        run: npm install
        working-directory: test-eval

      - name: Run eval-action
        uses: step-security/eval-action@release
        with:
          api_key: ${{ secrets.BRAINTRUST_API_KEY }}
          runtime: node
          use_proxy: 'false'
          root: test-eval
          paths: trivial.eval.ts
