
name: fetch-gh-release-asset

on:
  workflow_dispatch:

jobs:
  download:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest

        version:
          - 'tags/v92.12.0'

    name: Download
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6
      - name: Create a subdirectory
        run: mkdir -p subdir || true
        shell: bash
      - name: Get a specific version
        id: get_release
        uses: step-security/fetch-gh-release-asset@main
        with:
          repo: 'step-security/workflow-playground'
          version: ${{ matrix.version }}
          file: 'README.2.md'
          target: 'subdir/README.2.md'
      - name: Display the outputs
        run: |
          echo "${{ steps.get_release.outputs.version }}"
          echo "${{ steps.get_release.outputs.name }}"
          echo "${{ steps.get_release.outputs.body }}"
