name: fossa-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: FOSSA Scan
        uses: step-security/fossa-action@release
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
