name: get-pr-commits

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'testdata/get-pr-commits/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  get-pr-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Get PR Commits
        id: get-commits
        uses: step-security/get-pr-commits@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print commits
        run: echo '${{ steps.get-commits.outputs.commits }}'
