name: get-secretmanager-secrets
on: 
  workflow_dispatch:

jobs:
    secret:
        runs-on: ubuntu-latest
        steps:  
            - name: get-secret
              uses: step-security/get-secretmanager-secrets@main
              with:
                secrets: password