name: gha-setup-swift

on:
  workflow_dispatch:


jobs:
  gha-setup-swift-main:
    runs-on: windows-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Swift toolchain (official)
        uses: step-security/gha-setup-swift@main
        with:
          swift-version: swift-6.0.3-release
          swift-build: 6.0.3-RELEASE

      - name: Show Swift version
        shell: pwsh
        run: |
          swift --version
