name: gha-setup-vsdevenv

on:
  workflow_dispatch:
jobs:
  build-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Visual Studio devenv environment
        id: vs
        uses: step-security/gha-setup-vsdevenv@main
