name: ghaction-setup-containerd

on:
  workflow_dispatch:

jobs:
  containerd-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up containerd
        uses: step-security/ghaction-setup-containerd@main
