name: github-app-auth-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  github-app-auth-action-main:
    name: GitHub App Auth (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get GitHub App Token
        id: auth
        continue-on-error: true
        uses: step-security/github-app-auth-action@release
        with:
          creds: ${{ secrets.GITHUB_APP_CREDS }}
