name: handlebars-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  handlebars-action:
    name: handlebars-action
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run handlebars-action
        uses: step-security/handlebars-action@main
        with:
          files: testdata/handlebars-action/*.template

      - name: Verify output
        run: cat testdata/handlebars-action/test.txt
