name: import-codesign-certs

on:
  workflow_dispatch:

jobs:
  test-import-certs:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Apple code-signing certificates
        uses: step-security/import-codesign-certs@main
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}

      - name: Verify imported identities
        run: security find-identity -v -p codesigning
