name: list-files-action

on: 
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: list-files
        uses: step-security/list-files-action@main
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".yml"
