name: "load-secrets-action"
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  load-secrets-main:
    name: Load Secrets (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load secrets from 1Password
        uses: step-security/load-secrets-action@main
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        with:
          export-env: "false"
