name: lock-threads

on: 
  workflow_dispatch:

jobs:
  lock-threads-main:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit
      - name: Lock Threads
        uses: step-security/lock-threads@release
        with:
          issue-inactive-days: "365"
          pr-inactive-days: "365"
          discussion-inactive-days: "365"
          issue-lock-reason: "resolved"
          pr-lock-reason: "resolved"
          log-output: "true"
