name: markdownlint-cli2-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  markdownlint-cli2-main:
    name: Markdownlint CLI2 Action (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint Markdown files
        uses: step-security/markdownlint-cli2-action@main
        continue-on-error: true
        with:
          globs: "**/*.md"
