name: maturin-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  maturin-action-main:
    name: Maturin Build (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Maturin
        uses: step-security/maturin-action@release
        with:
          command: build
          args: --release
