name: maven-dependency-submission-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: write
jobs:
  maven-dependency-submission-main:
    name: Maven Dependency Submission (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Maven Dependency Submission
        uses: step-security/maven-dependency-submission-action@release
        with:
          directory: ${{ github.workspace }}
          token: ${{ github.token }}
  test-main-basic:
    name: Test Main - Basic
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run Main Action
        uses: step-security/maven-dependency-submission-action@release
        with:
          directory: test-data/maven/simple
          token: ${{ github.token }}
  test-main-with-arguments:
    name: Test Main - With Arguments
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run Main Action
        uses: step-security/maven-dependency-submission-action@release
        with:
          directory: test-data/maven/simple
          maven-args: ' -X -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
          token: ${{ github.token }}
