name: maven-dependency-submission-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: write
jobs:
  test-main-basic:
    name: Test Main - Basic
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run Main Action
        uses: step-security/maven-dependency-submission-action@release
        with:
          directory: test-data/maven/simple
          token: ${{ github.token }}

