name: multi-labeler

on:
  pull_request_target:
  pull_request:
  issues:
  issue_comment:

permissions:
  contents: read  
  issues: write         
  pull-requests: write    
  statuses: write  
  checks: write             

jobs:
  labeler:
    name: Multi Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/multi-labeler@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/labeler.yml
