name: node-pr-labeler

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'testdata/node-pr-labeler/**'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  node-pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Label PR
        uses: step-security/node-pr-labeler@release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/node-pr-labeler.yml
