name: opencode-action

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  opencode-action:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run opencode
        uses: step-security/opencode-action@main
        with:
          model: anthropic/claude-sonnet-4-6
          use_github_token: "true"
          prompt: "Say hello world"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
