name: pr-lint-action

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - 'testdata/pr-lint-action/test-change.txt'

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  pr-lint-action-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run pr-lint-action
        uses: step-security/pr-lint-action@main
        with:
          title-regex: '^(feat|fix|chore|docs|refactor|test|ci)(\(.+\))?: .+'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
