name: publish-to-bcr

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create registry
        run: |
          mkdir -p bazel-central-registry/modules
          cd bazel-central-registry && git init

      - name: Publish to BCR
        uses: step-security/publish-to-bcr@main
        with:
          tag: main
          module-version: 0.0.0
          github-repository: maintained-actions-test/public-test
          templates-dir: .bcr
          local-registry: bazel-central-registry

  test-publish-workflow:
    uses: step-security/publish-to-bcr/.github/workflows/publish.yaml@main
    with:
      tag_name: main
      registry_fork: step-security/bazel-central-registry
      attest: false
      open_pull_request: false
      download_default_release_artifacts: false
      repository: maintained-actions-test/public-test
    secrets:
      publish_token: ${{ secrets.GITHUB_TOKEN }}
