name: pull-request-comment-trigger
on: 
  workflow_dispatch:

jobs:
    notification:
        runs-on: ubuntu-latest
        steps:
            - name: trigger
              uses: step-security/pull-request-comment-trigger@main
              with:
                trigger: "new"
