name: quarto-actions

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  subscription-check:
    name: Subscription Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and print quarto version
        uses: step-security/quarto-actions/setup@main
        with:
          version: release

      - run: quarto --version

      - name: Render using quarto
        uses: step-security/quarto-actions/render@main
        with:
          path: ./quarto
