name: read-yaml
on: 
  workflow_dispatch:

jobs:
    read-yaml:
        runs-on: ubuntu-latest
        steps:  
            - uses: actions/checkout@v6
            - name: read-yaml
              uses: step-security/read-yaml@main
              with:
                file: './.github/labeler.yml'
                key-path: '["version"]'
                
