name: readmeio-rdme
on: 
  workflow_dispatch:

jobs:
    readme:
        runs-on: ubuntu-latest
        steps:  
            - uses: actions/checkout@v6
            - name: openapi validate
              uses: step-security/readmeio-rdme@main
              with:
               rdme: openapi validate openapi.json
