name: rsdoctor-action

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write

jobs:
  rsdoctor-action:
    name: Rsdoctor Action
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build Demo Projects
        run: |
          cd testdata/rsdoctor-action/rsbuild-demo
          npm install
          npm run build
          cd ../rsbuild-demo2
          npm install
          npm run build

      - name: Report Bundle Size
        uses: step-security/rsdoctor-action@main
        env:
          AI_TOKEN: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file_path: 'testdata/rsdoctor-action/**/dist/rsdoctor-data.json'
          target_branch: main
          ai_model: claude-3-5-haiku-latest
