name: run-report-action

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install moon
        run: npm install -g @moonrepo/cli

      - name: Run moon ci
        run: moon ci

      - name: Report moon CI results
        uses: step-security/run-report-action@release
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
