name: secrets-fetch-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  secrets-fetch-action:
    name: secrets-fetch-action
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run secrets-fetch-action
        uses: step-security/secrets-fetch-action@main
        with:
          doppler-token: dummy
          doppler-project: my-project
          doppler-config: prd
