name: "secrets sync action"

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test secrets synchronization
        uses: step-security/secrets-sync-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

