name: "secrets-sync-action"

on: 
    workflow_dispatch:

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@rc
      with:
        egress-policy: audit

    - uses: actions/checkout@v4
    - name: Test secrets synchronization (with @main)
      uses: step-security/secrets-sync-action@main
      with:
        SECRETS: ^FOO$
        REPOSITORIES: ^step-security/workflow-playground-2$
        DRY_RUN: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_SECRET_PREFIX: "TEST_ACTION_MAIN_"
      env:
        FOO: ${{ github.run_id }}
        FOOBAR: BAZ
