name: set-github-variable

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-gh-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Update GitHub variable
        uses: step-security/set-github-variable@main
        with:
          name: TEST_VARIABLE_UPDATE
          value: "1"
          repository: maintained-actions-test/public-test
          token: ${{ secrets.SET_GH_VARIABLE_TOKEN }}
