name: setup-ndk
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  setup-ndk-main:
    name: Setup Android NDK (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Android NDK (main)
        uses: step-security/setup-ndk@main
        with:
          ndk-version: "r21e"
          add-to-path: true
