name: setup-jfrog-cli

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest   # ← REQUIRED

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"

      - name: Setup JFrog CLI (default)
        uses: step-security/setup-jfrog-cli@main
