name: setup-nasm

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install NASM
        uses: step-security/setup-nasm@release
        with:
          version: 2.16.01

      - name: Verify NASM installation
        run: nasm -v

      - name: Check NASM path
        run: which nasm
