name: setup-kustomize

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Setup Kustomize
        uses: step-security/setup-kustomize@main
        with:
          kustomize-version: '5.x'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Kustomize installation
        run: kustomize version
