name: setup-xcode

on: 
  workflow_dispatch:


jobs:
  setup-xcode:
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Lint Workflows
        uses: step-security/setup-xcode@release
        with: 
            xcode-version: latest-stable
