name: "setup-ocaml"
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: write
jobs:
  setup-ocaml-main:
    name: Setup OCaml (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up OCaml
        uses: step-security/setup-ocaml@release
        with:
          ocaml-compiler: "5"

