name: setup-qemu-action
on:
  workflow_dispatch:
    inputs: {}
jobs:
  setup-qemu-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: qemu
        uses: step-security/setup-qemu-action@main
        with:
          platforms: all
      - name: test
        shell: bash
        run: |-
          # This should output "aarch64" if QEMU is working on an x86_64 host
          docker run --rm --platform linux/arm64 alpine uname -m
