name: ssh-key-action

on: 
    workflow_dispatch:

jobs:
    ssh-pem:
      name: Connect to github.com (PEM format)
      runs-on: ubuntu-latest
      steps:
      - name: Checkout source codes
        uses: actions/checkout@v4
      - name: Install SSH key
        uses: step-security/ssh-key-action@main
        with:
            key: ${{ secrets.SSH_KEY_PEM }}
            known_hosts: unnecessary
      - name: git clone through SSH
        run: git clone git@github.com:step-security/ssh-key-action.git tmp
