name: super-linter
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  super-linter-main:
    name: Super-Linter (main)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Super-Linter
        uses: step-security/super-linter@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: "true"
          FILTER_REGEX_INCLUDE: ".*\\.github/workflows/.*"
          VALIDATE_GITHUB_ACTIONS: "true"
          DISABLE_ERRORS: "true"
  super-linter-slim-main:
    name: Super-Linter Slim (main)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Super-Linter Slim
        uses: step-security/super-linter/slim@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: "true"
          FILTER_REGEX_INCLUDE: ".*\\.github/workflows/.*"
          VALIDATE_GITHUB_ACTIONS: "true"
          DISABLE_ERRORS: "true"
