name: swiftwasm-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  swiftwasm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with SwiftWasm
        uses: step-security/swiftwasm-action@release
        with:
          shell-action: swift --version
