name: swiftylab-ci

on:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    outputs:
      proceed: ${{ steps.precondition.outputs.proceed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check should proceed
        id: precondition
        uses: step-security/swiftylab-ci/actions/condition@main
        with:
          workflow: swiftylab-ci.yml
          files: |
            Sources/**/*.swift
            Tests/**/*
            Package*.swift
      - name: Setup repository
        if: steps.precondition.outputs.proceed == 'true'
        uses: step-security/swiftylab-ci/actions/setup@main
        with:
          swift: latest
