name: terraform-docs-action
on: 
  workflow_dispatch:

jobs:
    Generate-terraform-docs-main:
      name: Terraform docs main
      runs-on: ubuntu-latest
      steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v4

      - uses: step-security/terraform-docs-action@main
        with:
          working-dir: terraform
          output-file: USAGE.md
          indention: 3

