name: terraform-check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v7

      - name: Terraform check
        uses: dflook/terraform-check@v3
        with:
          path: testdata/dflook-terraform-check
