name: test-reporting

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Report tests
        uses: step-security/test-reporting@main
        with:
          name: smoke
          reporter: jest-junit
          path: testdata/test-reporting/junit.xml
