name: trivy-action
on:
  workflow_dispatch:
    inputs: {}
permissions:
  contents: read
jobs:
  trivy-action-main:
    name: Trivy Action (main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Trivy vulnerability scanner
        uses: step-security/trivy-action@release
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: "true"
          skip-files: "**/pom.xml"
