name: upload-dsyms-github-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-dsyms:
    runs-on: macos-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload dSYMs to Datadog
        uses: step-security/upload-dsyms-github-action@main
        with:
          api_key: xyz
          site: datadoghq.com
          dsym_paths: testdata/upload-dsyms-github-action/test-dsyms
          dry_run: "true"
