name: upload-cloud-storage
on: 
  workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: upload to gcs
              uses: step-security/upload-cloud-storage@main
              with:
                path: README.md
                destination: bucket
