name: "vitest-coverage-report-action"

on: 
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Vitest Coverage Report Action
        uses: step-security/vitest-coverage-report-action@main
