name: workflow-dispatch-test

on:
  workflow_dispatch:
    inputs:
      message:
        required: true

concurrency:
  group: pending-test
  cancel-in-progress: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 300
      - run: echo '${{ inputs.message }}'
