name: xcodebuild

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  xcodebuild:
    name: xcodebuild
    runs-on: macos-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run xcodebuild
        uses: step-security/xcodebuild@main
        with:
          platform: macOS
